//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.ItemLocalisations = new HashSet<ItemLocalisation>();
            this.ItemPrices = new HashSet<ItemPrices>();
        }
    
        public int ItemId { get; set; }
        public int ProductId { get; set; }
        public string AXItemId { get; set; }
        public string ItemSizeId { get; set; }
        public string ItemTypeId { get; set; }
        public string ItemBarcode { get; set; }
        public string ItemModifiedBy { get; set; }
        public string ItemModifiedDateTime { get; set; }
        public int StoreItemsStoreItemId { get; set; }
    
        public virtual Products Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLocalisation> ItemLocalisations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPrices> ItemPrices { get; set; }
        public virtual ItemDescriptions ItemDescription { get; set; }
        public virtual StoreItems StoreItem { get; set; }
        public virtual OrderLines OrderLine { get; set; }
    }
}
