//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPrices
    {
        public int PriceId { get; set; }
        public int ItemId { get; set; }
        public int CurrencyId { get; set; }
        public int PriceCodeId { get; set; }
        public string ItemPrice { get; set; }
    
        public virtual Items Item { get; set; }
        public virtual PriceCodes PriceCode { get; set; }
        public virtual Currencies Currency { get; set; }
    }
}
