//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merchants()
        {
            this.Stores = new HashSet<Stores>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int MerchantId { get; set; }
        public string MerchantName { get; set; }
        public string MerchantPhone { get; set; }
        public string MerchantEmail { get; set; }
        public string MerchantAddress { get; set; }
        public string MerchantCity { get; set; }
        public string MerchantPostCode { get; set; }
        public string MerchantCountry { get; set; }
        public string MerchantModifiedBy { get; set; }
        public string MerchantModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stores> Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
