//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderLines = new HashSet<OrderLines>();
            this.Payments = new HashSet<Payments>();
        }
    
        public int OrderId { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public string CashierName { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
        public decimal Discount { get; set; }
        public string Note { get; set; }
        public int MerchantId { get; set; }
        public int StoreId { get; set; }
    
        public virtual Currencies Currency { get; set; }
        public virtual Terminals Terminal { get; set; }
        public virtual Merchants Merchant { get; set; }
        public virtual Stores Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLines> OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
