//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stores()
        {
            this.StoreItems = new HashSet<StoreItems>();
            this.Terminals = new HashSet<Terminals>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int StoreId { get; set; }
        public int MerchantId { get; set; }
        public string StoreName { get; set; }
        public string StorePhone { get; set; }
        public string StoreEmail { get; set; }
        public string StoreAddress { get; set; }
        public string StoreCity { get; set; }
        public string StorePostCode { get; set; }
        public int PriceCodesPriceCodeId { get; set; }
        public string LegalUnitId { get; set; }
        public string StoreModifiedBy { get; set; }
        public string StoreModifiedDateTime { get; set; }
    
        public virtual Merchants Merchant { get; set; }
        public virtual PriceCodes PriceCode { get; set; }
        public virtual LegalUnits LegalUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreItems> StoreItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terminals> Terminals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
